blog_admin_homepage:
  path:   /
  defaults: { _controller: IncolabBlogBundle:Admin:index }
    
blog_admin_news_add:
  path:   /news_add
  defaults: { _controller: IncolabBlogBundle:Admin:newsAdd }

blog_admin_news_edit:
  path:    /news_edit/{slug}.html
  defaults: { _controller: IncolabBlogBundle:Admin:newsEdit }
  requirements:
    slug: "[A-z0-9_-]+"

blog_admin_news_delete:
  path:    /news_delete/{slug}
  defaults: { _controller: IncolabBlogBundle:Admin:newsDelete }
  requirements:
    slug: "[A-z0-9_-]+"
    
blog_admin_comment_delete:
  path:   /comment_delete/{slugNews}/{commentId}
  defaults: { _controller: IncolabBlogBundle:Admin:commentDelete }
  requirements:
    slugNews: "[A-z0-9_-]+"
    commentId: \d+